# -*- coding: utf-8 -*-
"""PORJECT 1 SOCIAL MEDIA BEHAVIOUR ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qkma4XliLvtMRwHd4uwPEWnGnIVCw48H
"""

#1.importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#2.loading the dataset
df = pd.read_csv("/content/social_media_user_behavior.csv")

#3.basic data exploration
df.head()
df.tail()
df.info()
df.describe()

# 4. Data Cleaning
#check for missing values
df.isnull().sum()

#check duplicate rows
df.duplicated().sum()

#remove duplicates
df.drop_duplicates(inplace=True)

#convert date column
df['account_join_date'] = pd.to_datetime(df['account_join_date'])

#check data types
df.dtypes

#create new features
df['account_age_days'] = (pd.Timestamp.today() - df['account_join_date']).dt.days

#engagement score
df['engagement_score'] = (
    df['likes_given_per_day'] +
    df['comments_per_day'] +
    df['shares_per_day']
)

#5.Exploratory Data Analysis
#Age Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=20, kde=True)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

"""#insight

1. Most users are between 20-35 years old.

2. younger audiences dominate social media usage.
"""

#Gender Distribution
plt.figure(figsize=(6,5))

df['gender'].value_counts().plot(kind='bar')

plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

"""#Insight
1. Male and Female users are almost balanced.

2. Prefer Not to say"category is smaller.
"""

#Most used Social Media Platform
plt.figure(figsize=(8,5))

sns.countplot(
    y=df['primary_platform'],
    order=df['primary_platform'].value_counts().index
)

plt.title("Most Used Social Media Platform")
plt.show()

"""#Insight
1. instagram, tiktok, and youtube dominate.

2. facebook usage is lower among younger users.
"""

#daily usage hours
plt.figure(figsize=(8,5))

sns.boxplot(x=df['daily_usage_hours'])

plt.title("Daily Usage Hours")
plt.show()

"""#insight
1. some users spend extremely high hours daily.

2. indicates additive behavior patterns.
"""

#average usage by platform
platform_usage = df.groupby('primary_platform')['daily_usage_hours'].mean().sort_values()

plt.figure(figsize=(8,5))

platform_usage.plot(kind='barh')

plt.title("Average Daily Usage Hours by Platform")
plt.xlabel("Hours")
plt.show()

"""#insight
1. tiktok and instagram users spend more time daily.

2. linkedin users usually spend lower time.
"""

#relationship between usage and mental health
plt.figure(figsize=(8,5))

sns.scatterplot(
    x='daily_usage_hours',
    y='self_reported_mental_health_score',
    data=df
)

plt.title("Usage Hours vs Mental Health Score")
plt.show()

"""#insight
1. higher usage often correlation with poorer mental health.

2. heavy scrolling impacts emotional wellbeing.
"""

#sleep disrution analysis
plt.figure(figsize=(8,5))

sns.countplot(
    y=df['sleep_disruption'],
    order=df['sleep_disruption'].value_counts().index
)

plt.title("Sleep Disruption Due to Social Media")
plt.show()

"""#Insights
1. many users report mild or moderate sleep disruption.

2. screen addiction affects sleep cycles.
"""

#profession vs daily usage
plt.figure(figsize=(12,6))

sns.boxplot(
    x='profession',
    y='daily_usage_hours',
    data=df
)

plt.xticks(rotation=45)

plt.title("Profession vs Daily Usage")
plt.show()

"""#isight
1. students and freelancers oftern spend more time online.

2. professionals show moderate usage patterns.
"""

#device preference
plt.figure(figsize=(6,5))

df['preferred_device'].value_counts().plot(kind='pie', autopct='%1.1f%%')

plt.title("Preferred Device")
plt.ylabel("")
plt.show()

"""#insight
1. mobile devices dominate social media consumption.

2. desktop usage is comparatively lower
"""

#correlation heatmap
numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(14,8))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

"""#Insight
strong relationships may exists between
1. daily usage hours - sessions per day.
2. likes - comments - shares
3. engagement - followers count.
"""

#6. advance analysis
#top 10 most engaged users
top_users = df.sort_values(
    by='engagement_score',
    ascending=False
)[['user_id','engagement_score']].head(10)

print(top_users)

#average spending via social media
avg_spend = df['monthly_spend_via_social_usd'].mean()

print("Average Monthly Spend:", avg_spend)

#users concerned about screen time
df['screen_time_concern'].value_counts()

"""#7. insight
1. Younger users domain
most active users belong to younger age groups.

2. short video platforms create highest engagements - tiktok and instagram consume maximum user attention.

3. high usage impacts mental health - heavvy users report worse emotional wellbeing and sleep disruption.

4. mobile is the main device - almost all engagement happens through smartphones.

5. engagement metrics move together - likes, comments, and shares strongly correlate.

# 8. recommendations
for business
1. focus marketing on instagram and tiktok.
2. use short form of video content
3. optimize campaigns for mobile users.

#for platform users
1. introduce screen time reminders
2. improve wellbeing features.
3. reduce addictive notification systems.
"""

#9.export cleaned dataset
df.to_csv("cleaned_social_media_data.csv", index=False)

"""#10. Project title
Social Media User Behavior Analysis Using python.

tools used
1. python
2. pandas
3. numpy
4. matplotlib
5. seaborn

Project Workflow
1. data cleaning
2. feature engineering
3. Exploratory Data Analysis
4. Visualization.
5. Insights and Recommendations
"""